import turtle
wn = turtle.Screen()
t = turtle.Turtle()
turtle.title("Bangladesh")
t.fillcolor("green")
t.begin_fill()
t.fd(350)
t.rt(90)
t.fd(300)
t.rt(90)
t.fd(350)
t.rt(90)
t.fd(300)
t.end_fill()
t.penup()
t.goto(250,-150)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.circle(60)
t.end_fill()
